# Terminalizer configuration
frames: 50
frameDelay: auto
maxIdleTime: 2
cursorStyle: block
fontFamily: "Monaco, Lucida Console, Ubuntu Mono, Monospace"
fontSize: 14
lineHeight: 1
letterSpacing: 0
theme:
  background: "#1a1b26"
  foreground: "#c0caf5"
  cursor: "#c0caf5"
  black: "#1a1b26"
  red: "#f7768e"
  green: "#9ece6a"
  yellow: "#e0af68"
  blue: "#7aa2f7"
  magenta: "#bb9af7"
  cyan: "#7dcfff"
  white: "#a9b1d6"
  brightBlack: "#414868"
  brightRed: "#f7768e"
  brightGreen: "#9ece6a"
  brightYellow: "#e0af68"
  brightBlue: "#7aa2f7"
  brightMagenta: "#bb9af7"
  brightCyan: "#7dcfff"
  brightWhite: "#c0caf5"