name: Build wheels, RPM, DEB

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: |
          python -m pip install --upgrade build fpm
          python -m build
          fpm -s python -t deb dist/*.whl --name telert -f
          fpm -s python -t rpm dist/*.whl --name telert -f
      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: "*.deb\n*.rpm\ndist/*.whl"
      - uses: softprops/action-gh-release@v2
        with:
          files: "*.deb,*.rpm,dist/*.whl"