# .github/workflows/publish.yml  (add to the existing build job or separate)
permissions:
  id-token: write
  contents: read

jobs:
  pypi:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with: {name: packages}
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
